custom_service_name: "CI checker"
subprojects:
  - id: "Unit Tests 3x-PyTorch workflow"
    paths:
      - "neural_compressor/common/**"
      - "neural_compressor/torch/**"
      - "test/3x/torch/**"
      - "test/3x/common/**"
      - "setup.py"
      - "requirements_pt.txt"
      - ".azure-pipelines/scripts/ut/3x/collect_log_3x.sh"
    checks:
      - "UT-3x-Torch"
      - "UT-3x-Torch (Coverage Compare CollectDatafiles)"
      - "UT-3x-Torch (Unit Test 3x Torch Unit Test 3x Torch)"
      - "UT-3x-Torch (Unit Test 3x Torch baseline Unit Test 3x Torch baseline)"
